lang: ja
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
exclude:
  - README.md
locale: ja_JP
title: "HUIT ROADMAP"
minimal_mistakes_skin: "air"
show_date: true
search: true
logo: "/assets/images/huit-logo.png"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

twitter:
  username: "huitgroup"
author-profile: true
author:
  name     : "HUIT"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/huitgroup"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HUITGroup"

---
toc: true
toc_label: "My Table of Contents"
toc_icon: "cog"
---
