lang: ja
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# minimal mistakes settings
locale: ja_JP
title: "HUIT ROADMAP"
minimal_mistakes_skin: "air" # 全体の色合い
show_date: true
search: true
logo: "/assets/images/huit-logo.png"
include:
  - _pages

twitter:
  username: "huitgroup"
author-profile: true
author:
  name     : "HUIT"
  avatar   : "/assets/images/huit-logo.png"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/huitgroup"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HUITGroup"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      # Table of contents
      toc: true
      toc_label: "My Table of Contents"
      toc_icon: "cog"
      # header
      header:
        overlay_image: /assets/images/header.jpg
        overlay_filter: 0.5
        caption: "Photo credit: [**Unsplash**](https://unsplash.com)"



