lang: ja
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
exclude:
  - README.md
locale: ja_JP
title: "HUIT ROADMAP"
minimal_mistakes_skin: "default"
masthead_title: "HUIT-ROADMAP"
show_date: true
search: true

twitter:
  username: "huitgroup"

author:
  name     : "HUIT"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/huitgroup"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HUITGroup"

---
toc: true
toc_label: "My Table of Contents"
toc_icon: "cog"
---
